apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: demo-devops-test
  name: demo-devops-bc
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 9000
    type: HTTP
    requestPath: /api/users/health